# Generated by Django 4.2.22 on 2025-06-07 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thoughtnodes', '0004_thoughtnode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtnode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
