# Generated by Django 4.2.22 on 2025-06-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtnodes', '0005_alter_thoughtnode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtnode',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
