# Generated by Django 4.2.22 on 2025-06-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtnodes', '0007_alter_thoughtnode_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoughtnode',
            old_name='name',
            new_name='title',
        ),
    ]
