# Generated by Django 4.2.22 on 2025-06-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtnodes', '0008_rename_name_thoughtnode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtnode',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
