# Generated by Django 4.2.22 on 2025-06-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtnodes', '0010_alter_thoughtnode_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtnode',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=7),
        ),
    ]
