# Generated by Django 5.2.4 on 2025-07-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtnodes', '0011_alter_thoughtnode_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoughtnode',
            old_name='description',
            new_name='query',
        ),
    ]
